[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_source =  'let NERDTreeShowHidden = 1'


[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source =' let g:indent_guides_enable_on_vim_startup = 1'

[[plugins]]
repo = 't9md/vim-quickhl'

